# Generated by Django 4.1.5 on 2023-01-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='user',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
