# Generated by Django 4.1.5 on 2023-02-02 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallpapers', '0005_remove_comment_post_comment_wallpaper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaper',
            name='user',
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='owner',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='wallpapers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
